app:
  name: flask-app
  containerPort: 5000

image:
  repository: chandansyd05/flask-k8-app
  tag: "fe814e2"
  pullPolicy: Always
  # Optionally specify imagePullSecrets when pulling from private registries
  pullSecrets: []

replicaCount: 1

resources:
  limits: {}
  requests: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  host: chandan.world
  path: /
  secretName: qr-tls
  namespaceLabel: ingress-nginx
  podSelector:
    app.kubernetes.io/name: ingress-nginx

rbac:
  create: true
  serviceAccountName: flask-app-sa

networkPolicy:
  enabled: true

readinessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 5

