image:
  repository: chandansyd05/flask-k8-app
  tag: latest
containerPort: 5000

ingress:
  host: chandan.world
  secretName: qr-tls
  path: /

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

