image:
  repository: chandansyd05/flask-k8-app
  tag: latest
containerPort: 5000

ingress:
  host: chandan.world
  secretName: qr-tls
  path: /

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

rbac:
  create: true
  serviceAccount:
    name: flask-app-sa

networkPolicy:
  enabled: true
  ingress:
    from:
      app.kubernetes.io/name: ingress-nginx
service:
  port: 5000

