name: Build and Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app ./helm/helm-chart \
          --namespace default \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-k8-app \
          --set image.tag=latest
