name: Build and Deploy Flask App

on:
  push:
    branches: [ "add-workflow-dispatch" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Configure kubeconfig
        env:
          K8S_PRIMARY: ${{ secrets.KUBECONFIG }}
          K8S_FALLBACK: ""
        run: |
          if [ -n "$K8S_PRIMARY" ]; then
            VAL="$K8S_PRIMARY"
          elif [ -n "$K8S_FALLBACK" ]; then
            VAL="$K8S_FALLBACK"
          else
            echo "Neither KUBECONFIG nor KUBE_CONFIG secret is set. Add one to repository secrets."
            exit 1
          fi

          OUT_FILE="${{ github.workspace }}/kubeconfig.yaml"

          if echo "$VAL" | base64 --decode >/dev/null 2>&1; then
            echo "$VAL" | base64 --decode > "$OUT_FILE"
          else
            echo "$VAL" > "$OUT_FILE"
          fi

          chmod 600 "$OUT_FILE"
          echo "Wrote kubeconfig to $OUT_FILE"
          kubectl --kubeconfig="$OUT_FILE" config view -o jsonpath='{.clusters[0].cluster.server}' || true

      - name: Validate cluster access
        run: kubectl cluster-info || true

      - name: Delete existing Deployment
        run: kubectl delete deployment/flask-app --namespace default --ignore-not-found || true

      - name: Helm Upgrade & Install
        run: |
          helm upgrade --install flask-app ./helm/helm-chart \
            --namespace default \
            --values ./helm/helm-chart/values.yaml

      - name: Verify Deployment
        run: kubectl rollout status deployment/flask-app --namespace default
