name: Build and Deploy Flask App

on:
  push:
    branches: [ "add-workflow-dispatch" ]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend deps
        working-directory: ./frontend
        run: |
          if [ -f package-lock.json ]; then npm ci --legacy-peer-deps; else npm install; fi

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload static artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: frontend-static
          path: ./static

  build-and-deploy:
    name: Build & Deploy Backend
    runs-on: [self-hosted]
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download frontend static
        uses: actions/download-artifact@v4
        with:
          name: frontend-static
          path: .

      - name: Place frontend artifact in repo root
        run: |
          echo "Ensuring frontend static files are at ./static"
          if [ -d ./frontend-static/static ]; then
            mv ./frontend-static/static ./static
          elif [ -d ./frontend-static ]; then
            # Move all files from artifact root into repo root
            mv ./frontend-static/* . || true
            # If static exists inside moved files, normalize location
            if [ -d ./static ]; then
              echo "static directory ready"
            fi
          else
            echo "No frontend-static artifact directory found; continuing"
          fi

      - name: Debug workspace before build
        run: |
          echo "Workspace listing:"; ls -la
          echo "Find any static directories:"; find . -maxdepth 3 -type d -name static -print || true
          echo "Contents of ./static (if present):"; ls -la ./static || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1

      - name: Configure kubeconfig
        env:
          K8S_PRIMARY: ${{ secrets.KUBECONFIG }}
          K8S_FALLBACK: ""
        run: |
          if [ -n "$K8S_PRIMARY" ]; then
            VAL="$K8S_PRIMARY"
          elif [ -n "$K8S_FALLBACK" ]; then
            VAL="$K8S_FALLBACK"
          else
            echo "Neither KUBECONFIG nor KUBE_CONFIG secret is set. Add one to repository secrets."
            exit 1
          fi

          OUT_FILE="${{ github.workspace }}/kubeconfig.yaml"

          if echo "$VAL" | base64 --decode >/dev/null 2>&1; then
            echo "$VAL" | base64 --decode > "$OUT_FILE"
          else
            echo "$VAL" > "$OUT_FILE"
          fi

          chmod 600 "$OUT_FILE"
          echo "Wrote kubeconfig to $OUT_FILE"
          kubectl --kubeconfig="$OUT_FILE" config view -o jsonpath='{.clusters[0].cluster.server}' || true

      - name: Validate cluster access
        run: kubectl cluster-info || true

      - name: Delete existing Deployment
        run: kubectl delete deployment/flask-app --namespace default --ignore-not-found || true

      - name: Helm Upgrade & Install
        run: |
          helm upgrade --install flask-app ./helm/helm-chart \
            --namespace default \
            --values ./helm/helm-chart/values.yaml

      - name: Verify Deployment
        run: kubectl rollout status deployment/flask-app --namespace default
