name: Build and Deploy Flask App

on:
  push:
    branches: [ "current" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest

 # Set up Helm CLI
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.1  # or latest stable

    # Create kubeconfig file from GitHub Secret
    - name: Write kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yml

    # Optional: Confirm cluster connectivity
    - name: Validate cluster access
      env:
        KUBECONFIG: kubeconfig.yml
      run: kubectl cluster-info
    
    # Delete existing deployment
    - name: Delete existing Deployment
      run: kubectl delete deployment/flask-app --namespace default --kubeconfig ~/.kube/config --ignore-not-found

    # Deploy with Helm
    - name: Helm Upgrade & Install
      env:
        KUBECONFIG: kubeconfig.yml
      run: |
        helm upgrade --install flask-app ./helm/helm-chart \
          --namespace default \
          --values ./helm/helm-chart/values.yaml
    
    #verify deployment
    - name: Verify Deployment
      run: kubectl rollout status deployment/flask-app --namespace default --kubeconfig ~/.kube/config
