name: Build and Deploy Flask App

on:
  push:
    branches: [ "add-workflow-dispatch" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-k8-app:latest

 # Set up Helm CLI
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.1  # or latest stable

    # Create kubeconfig file from GitHub Secret
    - name: Write kubeconfig
      run: |
        # Accept either a plain kubeconfig or a base64-encoded kubeconfig in the secret.
        if echo "${{ secrets.KUBECONFIG }}" | base64 --decode > /dev/null 2>&1; then
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yml
        else
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yml
        fi
        export KUBECONFIG=$(pwd)/kubeconfig.yml


    # Optional: Confirm cluster connectivity
    - name: Validate cluster access
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yml
        # Show the cluster API server endpoint (helps debug network reachability)
        kubectl config view --kubeconfig kubeconfig.yml -o jsonpath="{.clusters[0].cluster.server}" || true
        kubectl cluster-info --kubeconfig kubeconfig.yml

    # Delete existing deployment
    - name: Delete existing Deployment
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yml
        kubectl delete deployment/flask-app --namespace default --kubeconfig kubeconfig.yml --ignore-not-found

    # Deploy with Helm
    - name: Helm Upgrade & Install
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yml
        helm upgrade --install flask-app ./helm/helm-chart \
          --namespace default \
          --values ./helm/helm-chart/values.yaml
    
    #verify deployment
    - name: Verify Deployment
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yml
        kubectl rollout status deployment/flask-app --namespace default --kubeconfig kubeconfig.yml
