name: Build and push Docker image

on:
  push:
    branches: [ add-workflow-dispatch ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional override tag (defaults to short commit SHA)"
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compute image tags
        id: vars
        shell: bash
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            TAG_OVERRIDE="${{ github.event.inputs.tag }}"
            echo "Using override tag: ${TAG_OVERRIDE}"
            echo "TAGS=chandansyd05/flask-k8-app:${TAG_OVERRIDE}" >> $GITHUB_OUTPUT
          else
            echo "TAGS=chandansyd05/flask-k8-app:${SHORT_SHA},chandansyd05/flask-k8-app:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.TAGS }}
          build-args: |
            BUILDER_BASE=python:3.13-slim

      - name: Summary
        run: |
          echo "Pushed tags: ${{ steps.vars.outputs.TAGS }}" >> $GITHUB_STEP_SUMMARY
